version: 2

build:
  os: ubuntu-20.04
  apt_packages:
    - freeglut3
    - freeglut3-dev
    - libgstreamer1.0-dev
    - libgstreamer-plugins-base1.0-dev
    - gstreamer1.0-plugins-base
    - gstreamer1.0-plugins-good
    - gstreamer1.0-plugins-bad
    - gstreamer1.0-plugins-ugly
    - gstreamer1.0-libav
  tools:
    python: "3.9"

python:
  install:
    - method: pip
      path: .
      extra_requirements:
        - doc
